### PR TITLE
AsyncQueryProviders

### PR DESCRIPTION
**Pull request by srigaux**
The goal is to provide a way to query Salesforce objects in a LINQ like way:

```csharp
    var singleCase = await client
                    .Query<SfCase>()
                    .Select(c => new SfCase
                    {
                        Id = c.Id,
                        CaseNumber = c.CaseNumber,
                        SystemModstamp = c.SystemModstamp,
                        Account = new SfAccount
                        {
                            Name = c.Account.Name,
                            SystemModstamp = c.Account.SystemModstamp
                        },
                        Contact = new SfContact
                        {
                            Name = c.Contact.Name,
                            SystemModstamp = c.Contact.SystemModstamp
                        }
                    })
                    .FirstOrDefault();
```

### CODE REVIEW

**Comment by srigaux** [comment]
I forgot to credit https://github.com/dozer47528/LinqToSalesforce for the LinqProvider base code

**Comment by srigaux** [comment]
Would it be possible for you to release a pre-release version of the NuGet package?
Or do you want me to publish my own.?

**Comment by anthonyreilly** [comment]
This will be a very interesting feature, so I am planning on it, but this PR has several breaking changes and conflicts that I need to rework first - it is modifying several files and introducing breaking changes in the core library besides just adding the new feature. I have not had time to do this yet, I should have some time later this week.

**Comment by anthonyreilly** [comment]
Merged and published as a pre-release package: https://www.nuget.org/packages/NetCoreForce.Linq/

**Pull request closed without merging**
